# Assignment 6

# Import needed modules

In [34]:
from nltk.corpus import stopwords #you can remove stop words for speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

# Text Data 1 (FRENCH)

In [35]:
file = open("C:/Users/User/Downloads/french.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))
    

Paris, surnommée la Ville Lumière, est la capitale de la France et l'une des villes les plus emblématiques et romantiques du monde
Située au cœur du pays, sur la Seine, Paris est célèbre pour ses monuments historiques, sa gastronomie raffinée et son influence dans les domaines de la culture, de l'art, de la mode et du design
Le monument le plus emblématique de Paris est sans doute la Tour Eiffel, construite par Gustave Eiffel à l'occasion de l'Exposition universelle de 1889
Cette tour de fer de 324 mètres de haut est aujourd'hui l'un des sites les plus visités au monde.



# Our data: a list of sentences

In [36]:
print("Sentences are ", sentences)

Sentences are  [['Paris,', 'surnommée', 'la', 'Ville', 'Lumière,', 'est', 'la', 'capitale', 'de', 'la', 'France', 'et', "l'une", 'des', 'villes', 'les', 'plus', 'emblématiques', 'et', 'romantiques', 'du', 'monde'], ['Située', 'au', 'cœur', 'du', 'pays,', 'sur', 'la', 'Seine,', 'Paris', 'est', 'célèbre', 'pour', 'ses', 'monuments', 'historiques,', 'sa', 'gastronomie', 'raffinée', 'et', 'son', 'influence', 'dans', 'les', 'domaines', 'de', 'la', 'culture,', 'de', "l'art,", 'de', 'la', 'mode', 'et', 'du', 'design'], ['Le', 'monument', 'le', 'plus', 'emblématique', 'de', 'Paris', 'est', 'sans', 'doute', 'la', 'Tour', 'Eiffel,', 'construite', 'par', 'Gustave', 'Eiffel', 'à', "l'occasion", 'de', "l'Exposition", 'universelle', 'de', '1889'], ['Cette', 'tour', 'de', 'fer', 'de', '324', 'mètres', 'de', 'haut', 'est', "aujourd'hui", "l'un", 'des', 'sites', 'les', 'plus', 'visités', 'au', 'monde.\n']]


# Function to calculate similarity

In [37]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix

In [38]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Get the pagerank scores

In [39]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.25, 1: 0.25, 2: 0.25, 3: 0.25}


# Sort sentences by pagerank

In [40]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.25, ['Située', 'au', 'cœur', 'du', 'pays,', 'sur', 'la', 'Seine,', 'Paris', 'est', 'célèbre', 'pour', 'ses', 'monuments', 'historiques,', 'sa', 'gastronomie', 'raffinée', 'et', 'son', 'influence', 'dans', 'les', 'domaines', 'de', 'la', 'culture,', 'de', "l'art,", 'de', 'la', 'mode', 'et', 'du', 'design']), (0.25, ['Paris,', 'surnommée', 'la', 'Ville', 'Lumière,', 'est', 'la', 'capitale', 'de', 'la', 'France', 'et', "l'une", 'des', 'villes', 'les', 'plus', 'emblématiques', 'et', 'romantiques', 'du', 'monde']), (0.25, ['Le', 'monument', 'le', 'plus', 'emblématique', 'de', 'Paris', 'est', 'sans', 'doute', 'la', 'Tour', 'Eiffel,', 'construite', 'par', 'Gustave', 'Eiffel', 'à', "l'occasion", 'de', "l'Exposition", 'universelle', 'de', '1889']), (0.25, ['Cette', 'tour', 'de', 'fer', 'de', '324', 'mètres', 'de', 'haut', 'est', "aujourd'hui", "l'un", 'des', 'sites', 'les', 'plus', 'visités', 'au', 'monde.\n'])]


# Pick the top “n” sentences

In [41]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


# Finish off by printing summary

In [42]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Située au cœur du pays, sur la Seine, Paris est célèbre pour ses monuments historiques, sa gastronomie raffinée et son influence dans les domaines de la culture, de l'art, de la mode et du design. Paris, surnommée la Ville Lumière, est la capitale de la France et l'une des villes les plus emblématiques et romantiques du monde. Le monument le plus emblématique de Paris est sans doute la Tour Eiffel, construite par Gustave Eiffel à l'occasion de l'Exposition universelle de 1889


# Text Data 2 (SPANISH)

In [43]:
file = open("C:/Users/User/Downloads/spanish 2.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

España, oficialmente conocida como el Reino de España, es un país ubicado en el suroeste de Europa, en la Península Ibérica
Limita al noreste con Francia, al oeste con Portugal, al sur con el territorio británico de Gibraltar y el mar Mediterráneo, y al este y noreste con el mar Mediterráneo y el mar Cantábrico
España es conocida por su rica historia y diversidad cultural
Tiene una población de alrededor de 47 millones de personas y su capital es Madrid
Además del español, el país tiene varias lenguas regionales reconocidas, como el catalán, el gallego y el vasco.El turismo es una parte importante de la economía española, con millones de visitantes que llegan cada año para disfrutar de sus playas, su deliciosa gastronomía, su arquitectura impresionante y su rica herencia cultural
España también es famosa por sus festivales, como la Semana Santa, las Fallas de Valencia y la Feria de Abril en Sevilla.



# Our data: a list of sentences

In [44]:
print("Sentences are ", sentences)

Sentences are  [['España,', 'oficialmente', 'conocida', 'como', 'el', 'Reino', 'de', 'España,', 'es', 'un', 'país', 'ubicado', 'en', 'el', 'suroeste', 'de', 'Europa,', 'en', 'la', 'Península', 'Ibérica'], ['Limita', 'al', 'noreste', 'con', 'Francia,', 'al', 'oeste', 'con', 'Portugal,', 'al', 'sur', 'con', 'el', 'territorio', 'británico', 'de', 'Gibraltar', 'y', 'el', 'mar', 'Mediterráneo,', 'y', 'al', 'este', 'y', 'noreste', 'con', 'el', 'mar', 'Mediterráneo', 'y', 'el', 'mar', 'Cantábrico'], ['España', 'es', 'conocida', 'por', 'su', 'rica', 'historia', 'y', 'diversidad', 'cultural'], ['Tiene', 'una', 'población', 'de', 'alrededor', 'de', '47', 'millones', 'de', 'personas', 'y', 'su', 'capital', 'es', 'Madrid'], ['Además', 'del', 'español,', 'el', 'país', 'tiene', 'varias', 'lenguas', 'regionales', 'reconocidas,', 'como', 'el', 'catalán,', 'el', 'gallego', 'y', 'el', 'vasco.El', 'turismo', 'es', 'una', 'parte', 'importante', 'de', 'la', 'economía', 'española,', 'con', 'millones', 'de',

# Function to calculate similarity

In [45]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix

In [46]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Get the pagerank scores

In [47]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.16666666666666663, 1: 0.16666666666666663, 2: 0.16666666666666663, 3: 0.16666666666666663, 4: 0.16666666666666663, 5: 0.16666666666666663}


# Sort sentences by pagerank

In [48]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.16666666666666663, ['Tiene', 'una', 'población', 'de', 'alrededor', 'de', '47', 'millones', 'de', 'personas', 'y', 'su', 'capital', 'es', 'Madrid']), (0.16666666666666663, ['Limita', 'al', 'noreste', 'con', 'Francia,', 'al', 'oeste', 'con', 'Portugal,', 'al', 'sur', 'con', 'el', 'territorio', 'británico', 'de', 'Gibraltar', 'y', 'el', 'mar', 'Mediterráneo,', 'y', 'al', 'este', 'y', 'noreste', 'con', 'el', 'mar', 'Mediterráneo', 'y', 'el', 'mar', 'Cantábrico']), (0.16666666666666663, ['España,', 'oficialmente', 'conocida', 'como', 'el', 'Reino', 'de', 'España,', 'es', 'un', 'país', 'ubicado', 'en', 'el', 'suroeste', 'de', 'Europa,', 'en', 'la', 'Península', 'Ibérica']), (0.16666666666666663, ['España', 'también', 'es', 'famosa', 'por', 'sus', 'festivales,', 'como', 'la', 'Semana', 'Santa,', 'las', 'Fallas', 'de', 'Valencia', 'y', 'la', 'Feria', 'de', 'Abril', 'en', 'Sevilla.\n']), (0.16666666666666663, ['España', 'es', 'conocida', 'por', '

# Pick the top “n” sentences

In [49]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


# Finish off by printing summary

In [50]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Tiene una población de alrededor de 47 millones de personas y su capital es Madrid. Limita al noreste con Francia, al oeste con Portugal, al sur con el territorio británico de Gibraltar y el mar Mediterráneo, y al este y noreste con el mar Mediterráneo y el mar Cantábrico. España, oficialmente conocida como el Reino de España, es un país ubicado en el suroeste de Europa, en la Península Ibérica


# Text Data 3 (GERMAN)

In [51]:
file = open("C:/Users/User/Downloads/german.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))
    


Deutschland, offiziell die Bundesrepublik Deutschland genannt, liegt in Mitteleuropa und grenzt im Norden an die Nordsee, die Ostsee und Dänemark, im Osten an Polen und Tschechien, im Süden an Österreich und die Schweiz sowie im Westen an Frankreich, Luxemburg, Belgien und die Niederlande
Es ist das bevölkerungsreichste Land der Europäischen Union mit einer geschätzten Bevölkerung von etwa 83 Millionen Menschen.Die Hauptstadt von Deutschland ist Berlin, aber das Land hat auch viele andere bedeutende Städte wie Hamburg, München, Köln und Frankfurt
Deutschland ist bekannt für seine reiche Kultur, seine beeindruckende Geschichte und seine wirtschaftliche Stärke
Es ist eine parlamentarische Demokratie und ein föderaler Staat mit 16 Bundesländern.Deutschland hat eine vielfältige Landschaft, die von den Gebirgen der Alpen und des Schwarzwaldes bis zu den flachen Ebenen im Norden reicht
Das Land hat auch eine reiche kulturelle Tradition, die sich in der Literatur, der Musik, der Kunst und der

# Our data: a list of sentences

In [52]:
print("Sentences are ", sentences)

Sentences are  [['Deutschland,', 'offiziell', 'die', 'Bundesrepublik', 'Deutschland', 'genannt,', 'liegt', 'in', 'Mitteleuropa', 'und', 'grenzt', 'im', 'Norden', 'an', 'die', 'Nordsee,', 'die', 'Ostsee', 'und', 'Dänemark,', 'im', 'Osten', 'an', 'Polen', 'und', 'Tschechien,', 'im', 'Süden', 'an', 'Österreich', 'und', 'die', 'Schweiz', 'sowie', 'im', 'Westen', 'an', 'Frankreich,', 'Luxemburg,', 'Belgien', 'und', 'die', 'Niederlande'], ['Es', 'ist', 'das', 'bevölkerungsreichste', 'Land', 'der', 'Europäischen', 'Union', 'mit', 'einer', 'geschätzten', 'Bevölkerung', 'von', 'etwa', '83', 'Millionen', 'Menschen.Die', 'Hauptstadt', 'von', 'Deutschland', 'ist', 'Berlin,', 'aber', 'das', 'Land', 'hat', 'auch', 'viele', 'andere', 'bedeutende', 'Städte', 'wie', 'Hamburg,', 'München,', 'Köln', 'und', 'Frankfurt'], ['Deutschland', 'ist', 'bekannt', 'für', 'seine', 'reiche', 'Kultur,', 'seine', 'beeindruckende', 'Geschichte', 'und', 'seine', 'wirtschaftliche', 'Stärke'], ['Es', 'ist', 'eine', 'parlam

# Function to calculate similarity

In [53]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix 

In [54]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Get the pagerank scores

In [55]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.16666666666666663, 1: 0.16666666666666663, 2: 0.16666666666666663, 3: 0.16666666666666663, 4: 0.16666666666666663, 5: 0.16666666666666663}


# Sort sentences by pagerank

In [56]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.16666666666666663, ['Es', 'ist', 'eine', 'parlamentarische', 'Demokratie', 'und', 'ein', 'föderaler', 'Staat', 'mit', '16', 'Bundesländern.Deutschland', 'hat', 'eine', 'vielfältige', 'Landschaft,', 'die', 'von', 'den', 'Gebirgen', 'der', 'Alpen', 'und', 'des', 'Schwarzwaldes', 'bis', 'zu', 'den', 'flachen', 'Ebenen', 'im', 'Norden', 'reicht']), (0.16666666666666663, ['Es', 'ist', 'das', 'bevölkerungsreichste', 'Land', 'der', 'Europäischen', 'Union', 'mit', 'einer', 'geschätzten', 'Bevölkerung', 'von', 'etwa', '83', 'Millionen', 'Menschen.Die', 'Hauptstadt', 'von', 'Deutschland', 'ist', 'Berlin,', 'aber', 'das', 'Land', 'hat', 'auch', 'viele', 'andere', 'bedeutende', 'Städte', 'wie', 'Hamburg,', 'München,', 'Köln', 'und', 'Frankfurt']), (0.16666666666666663, ['Deutschland,', 'offiziell', 'die', 'Bundesrepublik', 'Deutschland', 'genannt,', 'liegt', 'in', 'Mitteleuropa', 'und', 'grenzt', 'im', 'Norden', 'an', 'die', 'Nordsee,', 'die', 'Ostse

# Pick the top “n” sentences

In [57]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


# Finish off by printing summary

In [58]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Es ist eine parlamentarische Demokratie und ein föderaler Staat mit 16 Bundesländern.Deutschland hat eine vielfältige Landschaft, die von den Gebirgen der Alpen und des Schwarzwaldes bis zu den flachen Ebenen im Norden reicht. Es ist das bevölkerungsreichste Land der Europäischen Union mit einer geschätzten Bevölkerung von etwa 83 Millionen Menschen.Die Hauptstadt von Deutschland ist Berlin, aber das Land hat auch viele andere bedeutende Städte wie Hamburg, München, Köln und Frankfurt. Deutschland, offiziell die Bundesrepublik Deutschland genannt, liegt in Mitteleuropa und grenzt im Norden an die Nordsee, die Ostsee und Dänemark, im Osten an Polen und Tschechien, im Süden an Österreich und die Schweiz sowie im Westen an Frankreich, Luxemburg, Belgien und die Niederlande
