# classwork 5

In [1]:
import pandas as pd
df = pd.read_json("C:/Users/User/Downloads/Arts_Crafts_and_Sewing_5.json",lines=True)
df.sample(10)


overall  verified   reviewTime      reviewerID        asin  \
87758         5      True   08 7, 2011   AI77E08GER5PS  B000WV064M   
480966        5      True   09 6, 2016  A121H8AV6M7S55  B00QTNQ05Q   
385530        5     False   11 6, 2015  A3VFECUAD7I6QH  B013W6VF16   
229684        5      True  08 11, 2017   AWYB3KA153Y5X  B0058V9KMK   
90935         4      True   04 7, 2016  A2RV3RVL9DPISK  B000X24A1K   
211059        5      True  10 28, 2013   AHLUGZHYSRR1O  B004E3S4AW   
93563         5      True  02 25, 2016  A1UA0831DNQSUD  B000XZTKDU   
338669        4      True  11 11, 2016   A1K1TKNDEVWIP  B00KIWIJIU   
272525        4      True  08 20, 2016  A3UHJDIBG1SA3K  B009OXJ1TU   
289929        5      True   10 1, 2015  A38CP8W13VGJS5  B00BWJCCI6   

                                                    style        reviewerName  \
87758                                                 NaN        D. Jorgensen   
480966                                                NaN           Barb Wolf   
385530                               {'Color:': ' Black'}               Kaaty   
229684                        {'Package Quantity:': ' 1'}         Michelle101   
90935                        {'Size:': ' 7" X 4" X 1.5"'}           Vaughanie   
211059                                                NaN  Connie L. Graybill   
93563                           {'Color:': ' Slate Grey'}       Joan K. Hurst   
338669                                {'Color:': ' Polo'}                 Jo8   
272525                                                NaN     Amazon Customer   
289929  {'Color:': ' Teal', 'Style Name:': ' Big Shot ...              daisey   

                                               reviewText  \
87758   My long needles fit fine and the case is well-...   
480966                           So easy and fast to use.   
385530  I love how these brush cases are made. Not onl...   
229684  It was my first time using a resin and I have ...   
90935                             works well for my beads   
211059  While you can roll your clay with anything you...   
93563    As described. Excellent product. Very satisfied.   
338669  Very soft yarn and the gorgeous colors were tr...   
272525         Was here quickly and the needles are great   
289929  I love this machine so far. I am just getting ...   

                                                  summary  unixReviewTime  \
87758                                        Very pleased      1312675200   
480966                                         Five Stars      1473120000   
385530                               Sturdy Brush Holder!      1446768000   
229684  I was both pleased and just a tiny bit disappo...      1502409600   
90935                                          Four Stars      1459987200   
211059                                          Wonderful      1382918400   
93563                   Excellent product. Very satisfied      1456358400   
338669                                    Beautiful yarn!      1478822400   
272525                 Great! Fantastically great needles      1471651200   
289929                                            Like it      1443657600   

       vote image  
87758     5   NaN  
480966  NaN   NaN  
385530    2   NaN  
229684  NaN   NaN  
90935   NaN   NaN  
211059  NaN   NaN  
93563   NaN   NaN  
338669  NaN   NaN  
272525  NaN   NaN  
289929    6   NaN

# Get the Bing Liu lexicon

In [2]:
from sklearn import preprocessing
import nltk
nltk.download('opinion_lexicon')
from nltk.corpus import opinion_lexicon
from nltk.tokenize import word_tokenize
print('Total number of words in opinion lexicon', len(opinion_lexicon.words()))
print('Examples of positive words in opinion lexicon',
opinion_lexicon.positive()[:10])
print('Examples of negative words in opinion lexicon',
opinion_lexicon.negative()[:10])

Total number of words in opinion lexicon 6789
Examples of positive words in opinion lexicon ['a+', 'abound', 'abounds', 'abundance', 'abundant', 'accessable', 'accessible', 'acclaim', 'acclaimed', 'acclamation']
Examples of negative words in opinion lexicon ['2-faced', '2-faces', 'abnormal', 'abolish', 'abominable', 'abominably', 'abominate', 'abomination', 'abort', 'aborted']


[nltk_data] Downloading package opinion_lexicon to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package opinion_lexicon is already up-to-date!


# creating the dictionary

In [3]:
# Let's create a dictionary which we can use for scoring our review text
nltk.download('punkt')
df.rename(columns={"reviewText": "text"}, inplace=True)
pos_score = 1
neg_score = -1
word_dict = {}
# Adding the positive words to the dictionary
for word in opinion_lexicon.positive():
  word_dict[word] = pos_score
# Adding the negative words to the dictionary
for word in opinion_lexicon.negative():
  word_dict[word] = neg_score

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


# function to do math

def bing_liu_score(text):
    sentiment_score = 0
    bag_of_words = word_tokenize(text.lower())
    for word in bag_of_words:
         if word in word_dict:
                sentiment_score += word_dict[word]
    return sentiment_score

In [5]:
df['text'].fillna('no review', inplace=True)
df['Bing_Liu_Score'] = df['text'].apply(bing_liu_score)

In [6]:
df[['overall',"text", 'Bing_Liu_Score']].head(10)

overall                                               text  Bing_Liu_Score
0        4                Contains some interesting stitches.               1
1        5  I'm a fairly experienced knitter of the one-co...              22
2        4  Great book but the index is terrible. Had to w...               0
3        5  I purchased the Kindle edition which is incred...               4
4        5  Very well laid out and very easy to read.\n\nT...               5
5        5  Beginning her career as a freelance knitter, M...              15
6        5  This is a terrific stitch handbook (and I have...               9
7        4  The book needs to be coil bound. The content i...               1
8        5  I really am enjoying this book! I like the siz...              12
9        5  Just received this book and looked over it cov...               6

In [7]:
df.groupby('overall').agg({'Bing_Liu_Score':'mean'})

Bing_Liu_Score
overall                
1             -0.255049
2              0.566098
3              1.158796
4              2.028146
5              2.130005

# Import needed modules

In [9]:
from nltk.corpus import stopwords #you can remove stop words for speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

# Text Data 1

In [68]:
file = open("C:/Users/User/Downloads/Text1.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))
    

It was the best of times
It was the worst of times
It was the age of wisdom
It was the age of foolishness
What is the importance of age
This is the best example.


# Our data: a list of sentences

In [69]:
print("Sentences are ", sentences)

Sentences are  [['It', 'was', 'the', 'best', 'of', 'times'], ['It', 'was', 'the', 'worst', 'of', 'times'], ['It', 'was', 'the', 'age', 'of', 'wisdom'], ['It', 'was', 'the', 'age', 'of', 'foolishness'], ['What', 'is', 'the', 'importance', 'of', 'age'], ['This', 'is', 'the', 'best', 'example.']]


# Function to calculate similarity

In [70]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix

In [71]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Get the pagerank scores

In [72]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.16666666666666663, 1: 0.16666666666666663, 2: 0.16666666666666663, 3: 0.16666666666666663, 4: 0.16666666666666663, 5: 0.16666666666666663}


# Sort sentences by pagerank

In [73]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.16666666666666663, ['What', 'is', 'the', 'importance', 'of', 'age']), (0.16666666666666663, ['This', 'is', 'the', 'best', 'example.']), (0.16666666666666663, ['It', 'was', 'the', 'worst', 'of', 'times']), (0.16666666666666663, ['It', 'was', 'the', 'best', 'of', 'times']), (0.16666666666666663, ['It', 'was', 'the', 'age', 'of', 'wisdom']), (0.16666666666666663, ['It', 'was', 'the', 'age', 'of', 'foolishness'])]


# Pick the top “n” sentences

In [74]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


# Finish off by printing summary

In [75]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 What is the importance of age. This is the best example.. It was the worst of times


# Text Data 2

In [43]:
file = open("C:/Users/User/Downloads/Text2.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

I AM SAM
I AM SAM
SAM I AM
THAT SAM-I-AM! THAT SAM-I-AM!
I DO NOT LIKE THAT SAM-I-AM!
DO WOULD YOU LIKE GREEN EGGS AND HAM?
I DO NOT LIKE THEM, SAM-I-AM
I DO NOT LIKE GREEN EGGS AND HAM
WOULD YOU LIKE THEM HERE OR THERE?
I WOULD NOT LIKE THEM HERE OR THERE
I WOULD NOT LIKE THEM ANYWHERE
I DO NOT LIKE GREEN EGGS AND HAM
I DO NOT LIKE THEM, SAM-I-AM
WOULD YOU LIKE THEM IN A HOUSE?
WOULD YOU LIKE THEN WITH A MOUSE?
I DO NOT LIKE THEM IN A HOUSE
I DO NOT LIKE THEM WITH A MOUSE
I DO NOT LIKE THEM HERE OR THERE
I DO NOT LIKE THEM ANYWHERE
I DO NOT LIKE GREEN EGGS AND HAM
I DO NOT LIKE THEM, SAM-I-AM.



# Our data: a list of sentences

In [44]:
print("Sentences are ", sentences)

Sentences are  [['I', 'AM', 'SAM'], ['I', 'AM', 'SAM'], ['SAM', 'I', 'AM'], ['THAT', 'SAM-I-AM!', 'THAT', 'SAM-I-AM!'], ['I', 'DO', 'NOT', 'LIKE', 'THAT', 'SAM-I-AM!'], ['DO', 'WOULD', 'YOU', 'LIKE', 'GREEN', 'EGGS', 'AND', 'HAM?'], ['I', 'DO', 'NOT', 'LIKE', 'THEM,', 'SAM-I-AM'], ['I', 'DO', 'NOT', 'LIKE', 'GREEN', 'EGGS', 'AND', 'HAM'], ['WOULD', 'YOU', 'LIKE', 'THEM', 'HERE', 'OR', 'THERE?'], ['I', 'WOULD', 'NOT', 'LIKE', 'THEM', 'HERE', 'OR', 'THERE'], ['I', 'WOULD', 'NOT', 'LIKE', 'THEM', 'ANYWHERE'], ['I', 'DO', 'NOT', 'LIKE', 'GREEN', 'EGGS', 'AND', 'HAM'], ['I', 'DO', 'NOT', 'LIKE', 'THEM,', 'SAM-I-AM'], ['WOULD', 'YOU', 'LIKE', 'THEM', 'IN', 'A', 'HOUSE?'], ['WOULD', 'YOU', 'LIKE', 'THEN', 'WITH', 'A', 'MOUSE?'], ['I', 'DO', 'NOT', 'LIKE', 'THEM', 'IN', 'A', 'HOUSE'], ['I', 'DO', 'NOT', 'LIKE', 'THEM', 'WITH', 'A', 'MOUSE'], ['I', 'DO', 'NOT', 'LIKE', 'THEM', 'HERE', 'OR', 'THERE'], ['I', 'DO', 'NOT', 'LIKE', 'THEM', 'ANYWHERE'], ['I', 'DO', 'NOT', 'LIKE', 'GREEN', 'EGGS', 'AN

# Function to calculate similarity

In [45]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix

In [46]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

# Get the pagerank scores

In [47]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.04761904761904764, 1: 0.04761904761904764, 2: 0.04761904761904764, 3: 0.04761904761904764, 4: 0.04761904761904764, 5: 0.04761904761904764, 6: 0.04761904761904764, 7: 0.04761904761904764, 8: 0.04761904761904764, 9: 0.04761904761904764, 10: 0.04761904761904764, 11: 0.04761904761904764, 12: 0.04761904761904764, 13: 0.04761904761904764, 14: 0.04761904761904764, 15: 0.04761904761904764, 16: 0.04761904761904764, 17: 0.04761904761904764, 18: 0.04761904761904764, 19: 0.04761904761904764, 20: 0.04761904761904764}


# Sort sentences by pagerank

In [48]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.04761904761904764, ['WOULD', 'YOU', 'LIKE', 'THEN', 'WITH', 'A', 'MOUSE?']), (0.04761904761904764, ['WOULD', 'YOU', 'LIKE', 'THEM', 'IN', 'A', 'HOUSE?']), (0.04761904761904764, ['WOULD', 'YOU', 'LIKE', 'THEM', 'HERE', 'OR', 'THERE?']), (0.04761904761904764, ['THAT', 'SAM-I-AM!', 'THAT', 'SAM-I-AM!']), (0.04761904761904764, ['SAM', 'I', 'AM']), (0.04761904761904764, ['I', 'WOULD', 'NOT', 'LIKE', 'THEM', 'HERE', 'OR', 'THERE']), (0.04761904761904764, ['I', 'WOULD', 'NOT', 'LIKE', 'THEM', 'ANYWHERE']), (0.04761904761904764, ['I', 'DO', 'NOT', 'LIKE', 'THEM,', 'SAM-I-AM.\n']), (0.04761904761904764, ['I', 'DO', 'NOT', 'LIKE', 'THEM,', 'SAM-I-AM']), (0.04761904761904764, ['I', 'DO', 'NOT', 'LIKE', 'THEM,', 'SAM-I-AM']), (0.04761904761904764, ['I', 'DO', 'NOT', 'LIKE', 'THEM', 'WITH', 'A', 'MOUSE']), (0.04761904761904764, ['I', 'DO', 'NOT', 'LIKE', 'THEM', 'IN', 'A', 'HOUSE']), (0.04761904761904764, ['I', 'DO', 'NOT', 'LIKE', 'THEM', 'HERE', 'OR

# Pick the top “n” sentences

In [49]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


# Finish off by printing summary

In [50]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 WOULD YOU LIKE THEN WITH A MOUSE?. WOULD YOU LIKE THEM IN A HOUSE?. WOULD YOU LIKE THEM HERE OR THERE?


# Text Data 3

In [60]:
file = open("C:/Users/User/Downloads/Text3.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))
    


As an institution of higher learning, Sacred Heart University places special emphasis on academic integrity, which is a commitment to the fundamental values of honesty, trust, fairness, respect, and responsibility
Only when these values are widely respected and practiced by all members of the University students, faculty, administrators, and staff can the University maintain a culture that promotes free exploration of knowledge, constructive debate, genuine learning, effective research, fair assessment of student progress, and development of members characters
These aims of the University require that its members exercise mutual responsibilities
At its core, academic integrity is secured by a principled commitment to carry out these responsibilities, not by rules and penalties
Students and faculty should strive to create an academic environment that is honest, fair, and respectful of all
They do this by evaluating others work fairly, by responding to others ideas critically yet courteo

# Our data: a list of sentences

In [61]:
print("Sentences are ", sentences)

Sentences are  [['As', 'an', 'institution', 'of', 'higher', 'learning,', 'Sacred', 'Heart', 'University', 'places', 'special', 'emphasis', 'on', 'academic', 'integrity,', 'which', 'is', 'a', 'commitment', 'to', 'the', 'fundamental', 'values', 'of', 'honesty,', 'trust,', 'fairness,', 'respect,', 'and', 'responsibility'], ['Only', 'when', 'these', 'values', 'are', 'widely', 'respected', 'and', 'practiced', 'by', 'all', 'members', 'of', 'the', 'University', 'students,', 'faculty,', 'administrators,', 'and', 'staff', 'can', 'the', 'University', 'maintain', 'a', 'culture', 'that', 'promotes', 'free', 'exploration', 'of', 'knowledge,', 'constructive', 'debate,', 'genuine', 'learning,', 'effective', 'research,', 'fair', 'assessment', 'of', 'student', 'progress,', 'and', 'development', 'of', 'members', 'characters'], ['These', 'aims', 'of', 'the', 'University', 'require', 'that', 'its', 'members', 'exercise', 'mutual', 'responsibilities'], ['At', 'its', 'core,', 'academic', 'integrity', 'is', 

# Function to calculate similarity

In [62]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix 

In [63]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Get the pagerank scores

In [64]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.09090909090909093, 1: 0.09090909090909093, 2: 0.09090909090909093, 3: 0.09090909090909093, 4: 0.09090909090909093, 5: 0.09090909090909093, 6: 0.09090909090909093, 7: 0.09090909090909093, 8: 0.09090909090909093, 9: 0.09090909090909093, 10: 0.09090909090909093}


# Sort sentences by pagerank

In [65]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.09090909090909093, ['Violations', 'of', 'academic', 'integrity', 'are', 'kept', 'on', 'file', 'second', 'violations', 'will', 'bring', 'additional', 'sanctions,', 'up', 'to', 'dismissal', 'from', 'the', 'University']), (0.09090909090909093, ['They', 'do', 'this', 'by', 'evaluating', 'others', 'work', 'fairly,', 'by', 'responding', 'to', 'others', 'ideas', 'critically', 'yet', 'courteously,', 'by', 'respecting', 'others', 'intellectual', 'and', 'physical', 'property,', 'and', 'by', 'nurturing', 'the', 'values', 'of', 'academic', 'integrity', 'in', 'all', 'contexts', 'of', 'University', 'life']), (0.09090909090909093, ['These', 'aims', 'of', 'the', 'University', 'require', 'that', 'its', 'members', 'exercise', 'mutual', 'responsibilities']), (0.09090909090909093, ['Students', 'and', 'faculty', 'should', 'strive', 'to', 'create', 'an', 'academic', 'environment', 'that', 'is', 'honest,', 'fair,', 'and', 'respectful', 'of', 'all']), (0.0909090

# Pick the top “n” sentences

In [66]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 2


# Finish off by printing summary

In [67]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Violations of academic integrity are kept on file second violations will bring additional sanctions, up to dismissal from the University. They do this by evaluating others work fairly, by responding to others ideas critically yet courteously, by respecting others intellectual and physical property, and by nurturing the values of academic integrity in all contexts of University life


# Text Data 4

In [78]:
file = open("C:/Users/User/Downloads/Text4.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Imagine there's no heaven
It's easy if you try
No hell below us
Above us, only sky
Imagine all the people livin' for today
Imagine there's no countries
It isn't hard to do
Nothing to kill or die for and no religion, too
Imagine all the people livin' life in peace
You may say I'm a dreamer but I'm not the only one
I hope someday you'll join us and the world will be as one
Imagine no possessions
I wonder if you can
No need for greed or hunger
A brotherhood of man
Imagine all the people sharing all the world




# Our data: a list of sentences

In [79]:
print("Sentences are ", sentences)

Sentences are  [['Imagine', "there's", 'no', 'heaven'], ["It's", 'easy', 'if', 'you', 'try'], ['No', 'hell', 'below', 'us'], ['Above', 'us,', 'only', 'sky'], ['Imagine', 'all', 'the', 'people', "livin'", 'for', 'today'], ['Imagine', "there's", 'no', 'countries'], ['It', "isn't", 'hard', 'to', 'do'], ['Nothing', 'to', 'kill', 'or', 'die', 'for', 'and', 'no', 'religion,', 'too'], ['Imagine', 'all', 'the', 'people', "livin'", 'life', 'in', 'peace'], ['You', 'may', 'say', "I'm", 'a', 'dreamer', 'but', "I'm", 'not', 'the', 'only', 'one'], ['I', 'hope', 'someday', "you'll", 'join', 'us', 'and', 'the', 'world', 'will', 'be', 'as', 'one'], ['Imagine', 'no', 'possessions'], ['I', 'wonder', 'if', 'you', 'can'], ['No', 'need', 'for', 'greed', 'or', 'hunger'], ['A', 'brotherhood', 'of', 'man'], ['Imagine', 'all', 'the', 'people', 'sharing', 'all', 'the', 'world'], ['\n']]


# Function to calculate similarity

In [80]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix 

In [81]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Get the pagerank scores

In [82]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.058823529411764705, 1: 0.058823529411764705, 2: 0.058823529411764705, 3: 0.058823529411764705, 4: 0.058823529411764705, 5: 0.058823529411764705, 6: 0.058823529411764705, 7: 0.058823529411764705, 8: 0.058823529411764705, 9: 0.058823529411764705, 10: 0.058823529411764705, 11: 0.058823529411764705, 12: 0.058823529411764705, 13: 0.058823529411764705, 14: 0.058823529411764705, 15: 0.058823529411764705, 16: 0.058823529411764705}


# Sort sentences by pagerank

In [83]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.058823529411764705, ['You', 'may', 'say', "I'm", 'a', 'dreamer', 'but', "I'm", 'not', 'the', 'only', 'one']), (0.058823529411764705, ['Nothing', 'to', 'kill', 'or', 'die', 'for', 'and', 'no', 'religion,', 'too']), (0.058823529411764705, ['No', 'need', 'for', 'greed', 'or', 'hunger']), (0.058823529411764705, ['No', 'hell', 'below', 'us']), (0.058823529411764705, ["It's", 'easy', 'if', 'you', 'try']), (0.058823529411764705, ['It', "isn't", 'hard', 'to', 'do']), (0.058823529411764705, ['Imagine', "there's", 'no', 'heaven']), (0.058823529411764705, ['Imagine', "there's", 'no', 'countries']), (0.058823529411764705, ['Imagine', 'no', 'possessions']), (0.058823529411764705, ['Imagine', 'all', 'the', 'people', 'sharing', 'all', 'the', 'world']), (0.058823529411764705, ['Imagine', 'all', 'the', 'people', "livin'", 'life', 'in', 'peace']), (0.058823529411764705, ['Imagine', 'all', 'the', 'people', "livin'", 'for', 'today']), (0.058823529411764705, 

# Pick the top “n” sentences

In [84]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


# Finish off by printing summary

In [85]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 You may say I'm a dreamer but I'm not the only one. Nothing to kill or die for and no religion, too. No need for greed or hunger


# Text data 5

In [86]:
file = open("C:/Users/User/Downloads/Text5.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

In an attempt to build an AI-ready workforce, Microsoft announced Intelligent Cloud Hub which has been launched to empower the next generation of students with AI-ready skills
Envisioned as a three-year collaborative program, Intelligent Cloud Hub will support around 100 institutions with AI infrastructure, course content and curriculum, developer support, development tools and give students access to cloud and AI services
As part of the program, the Redmond giant which wants to expand its reach and is planning to build a strong developer ecosystem in India with the program will set up the core AI infrastructure and IoT Hub for the selected campuses
The company will provide AI development tools and Azure AI services such as Microsoft Cognitive Services, Bot Services and Azure Machine Learning.According to Manish Prakash, Country General Manager-PS, Health and Education, Microsoft India, said, "With AI being the defining technology of our time, it is transIn an attempt to build an AI-re

# Our data: a list of sentences

In [87]:
print("Sentences are ", sentences)

Sentences are  [['In', 'an', 'attempt', 'to', 'build', 'an', 'AI-ready', 'workforce,', 'Microsoft', 'announced', 'Intelligent', 'Cloud', 'Hub', 'which', 'has', 'been', 'launched', 'to', 'empower', 'the', 'next', 'generation', 'of', 'students', 'with', 'AI-ready', 'skills'], ['Envisioned', 'as', 'a', 'three-year', 'collaborative', 'program,', 'Intelligent', 'Cloud', 'Hub', 'will', 'support', 'around', '100', 'institutions', 'with', 'AI', 'infrastructure,', 'course', 'content', 'and', 'curriculum,', 'developer', 'support,', 'development', 'tools', 'and', 'give', 'students', 'access', 'to', 'cloud', 'and', 'AI', 'services'], ['As', 'part', 'of', 'the', 'program,', 'the', 'Redmond', 'giant', 'which', 'wants', 'to', 'expand', 'its', 'reach', 'and', 'is', 'planning', 'to', 'build', 'a', 'strong', 'developer', 'ecosystem', 'in', 'India', 'with', 'the', 'program', 'will', 'set', 'up', 'the', 'core', 'AI', 'infrastructure', 'and', 'IoT', 'Hub', 'for', 'the', 'selected', 'campuses'], ['The', 'co

# Function to calculate similarity

In [88]:
def sentence_similarity(sent1, sent2 ):
 sent1 = [w.lower() for w in sent1]
 sent2 = [w.lower() for w in sent2]
 all_words = list(set(sent1 + sent2))
 vector1 = [0] * len(all_words)
 vector2 = [0] * len(all_words)
# build the vector for the first sentence
 for w in sent1:
  vector1[all_words.index(w)] += 1
# build the vector for the second sentence
 for w in sent2:
  vector2[all_words.index(w)] += 1
 return 1 - cosine_distance(vector1, vector2)

# Similarity matrix

In [89]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
 for idx2 in range(len(sentences)):
    if idx1 == idx2: #ignore if both are same sentences
      continue
      similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Get the pagerank scores

In [90]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.07692307692307691, 1: 0.07692307692307691, 2: 0.07692307692307691, 3: 0.07692307692307691, 4: 0.07692307692307691, 5: 0.07692307692307691, 6: 0.07692307692307691, 7: 0.07692307692307691, 8: 0.07692307692307691, 9: 0.07692307692307691, 10: 0.07692307692307691, 11: 0.07692307692307691, 12: 0.07692307692307691}


# Sort sentences by pagerank

In [91]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.07692307692307691, ['This', 'will', 'require', 'more', 'collaborations', 'and', 'training', 'and', 'working', 'with', 'AI']), (0.07692307692307691, ['This', 'program', 'also', 'included', 'developer-focused', 'AI', 'school', 'that', 'provided', 'a', 'bunch', 'of', 'assets', 'to', 'help', 'build', 'AI', 'skills.']), (0.07692307692307691, ['The', 'program', 'was', 'developed', 'to', 'provide', 'job', 'ready', 'skills', 'to', 'programmers', 'who', 'wanted', 'to', 'hone', 'their', 'skills', 'in', 'AI', 'and', 'data', 'science', 'with', 'a', 'series', 'of', 'online', 'courses', 'which', 'featured', 'hands-on', 'labs', 'and', 'expert', 'instructors', 'as', 'well']), (0.07692307692307691, ['The', 'program', 'is', 'an', 'attempt', 'to', 'ramp', 'up', 'the', 'institutional', 'set-up', 'and', 'build', 'capabilities', 'among', 'the', 'educators', 'to', 'educate', 'the', 'workforce', 'of', 'tomorrow."', 'The', 'program', 'aims', 'to', 'build', 'up', 

# Pick the top “n” sentences

In [92]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
  summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


# Printing Summary

In [93]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 This will require more collaborations and training and working with AI. This program also included developer-focused AI school that provided a bunch of assets to help build AI skills.. The program was developed to provide job ready skills to programmers who wanted to hone their skills in AI and data science with a series of online courses which featured hands-on labs and expert instructors as well
